import Header from "../../components/Header";
import Title from "../../components/common/title";
import Head from "next/head";
import { Box, Button, Heading, Image, Text, Tag } from "@chakra-ui/react";
import Tags from "../../components/common/Tags";

const ProductsPage = ({ productName, price }) => {
  return (
    <>
      <Head>
        <title>Viseur SX200 {productName} - Archerynted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Title title={"Viseur SX200"} />
      <Box
        mx="8"
        mt="12"
        p="8"
        bgColor={"blue.800"}
        borderRadius="md"
        display="flex"
        flexDirection={["column", "column", "column", "row"]}
        boxShadow="lg"
        mb="10"
      >
        <Box w={["100%", "100%", "100%", "calc(100%/ 3)"]}>
          <Image
            src="https://archerie-wuilbaut.eu/3695-superlarge_default/viseur-sx200-cl-de-arc-systeme.jpg"
            alt="viseur"
            w="100%"
            h="100%"
            borderRadius="md"
          />
        </Box>

        {/* Description produit + tags */}
        <Box
          w={["100%", "100%", "100%", "calc(100%/ 3)"]}
          p="8"
          texteAlign="center"
        >
          <Box
            display="flex"
            flexDirection="row"
            justifyContent="center"
            alignItems="center"
            my="4"
            flexWrap="wrap"
          >
            {/* TAGS */}
            <Tags colorScheme={"red"} size={"lg"} m="2" tagName="Arc System" />
            <Tags
              colorScheme={"blue"}
              size={"lg"}
              m="2"
              tagName="Arc Classique"
            />
            <Tags
              colorScheme={"green"}
              size={"lg"}
              m="2"
              tagName="Accessoire Viseur"
            />
          </Box>

          <Box mt="20" textAlign="center">
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Obcaecati repudiandae nam fugiat, sunt magnam esse animi assumenda
              voluptate? Itaque a, delectus sed obcaecati neque distinctio.
              Fugit hic delectus qui distinctio?
            </p>
          </Box>
        </Box>

        <Box
          w={["100%", "100%", "100%", "calc(100%/ 3)"]}
          p="8"
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDirection="column"
        >
          <Heading as="h4">{price}45.90€</Heading>
          <Button color="blue.500" bgColor="blue.100" my="4">
            Contacter le vendeur
          </Button>
        </Box>
      </Box>
    </>
  );
};

export default ProductsPage;
