import Head from "next/head";

import Header from "../../components/Header";
import Title from "../../components/common/title";
import Filters from "../../components/Filters";
import ProductBox from "../../components/common/ProductBox";
import CardProduct from "../../components/common/CardProduct";

const Products = () => {
  return (
    <>
      <Head>
        <title>Liste des Produits - Archerynted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Title title={"Produits"} />
      <Filters />
      <ProductBox>
      <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />        <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />
        <CardProduct />
      </ProductBox>
    </>
  )
}

export default Products;