import Head from "next/head";

import Header from "../components/Header";
import Title from "../components/common/title";
import Filters from "../components/Filters";

const Catégories = () => {
  return (
    <>
      <Head>
        <title>Catégories - Archerynted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Title title={"Catégories"} />
      <Filters />
    </>
  )
}

export default Catégories;