import Head from "next/head";

import Header from "../components/Header";
import Homes from "../components/Home";
import LatestProduct from "../components/Home/LatestProduct";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Archerynted - Achetez et Revendez vos produits d'archerie.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Homes />
      <LatestProduct />
    </>
  );
}
